name: Publish docker image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: "samsaadhanii"
  IMAGE_NAMESPACE_DOCKER: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAMESPACE_GHCR: ghcr.io/${{ github.repository_owner }}

jobs:
  push_to_registry:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Extract metadata for tagging image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAMESPACE_DOCKER }}/${{ env.IMAGE_REPOSITORY }}
            ${{ env.IMAGE_NAMESPACE_GHCR }}/${{ env.IMAGE_REPOSITORY }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
